/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface MenuItem {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'imageUrl' : string,
  'category' : string,
  'price' : number,
}
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'customerNote' : string,
  'status' : OrderStatus,
  'createdAt' : bigint,
  'items' : Array<OrderItem>,
  'totalPrice' : number,
}
export interface OrderItem {
  'name' : string,
  'specialInstructions' : string,
  'quantity' : bigint,
  'price' : number,
  'menuItemId' : bigint,
}
export type OrderStatus = { 'preparing' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'ready' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMenuItem' : ActorMethod<[string, string, number, string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrder' : ActorMethod<[string, string, Array<OrderItem>], bigint>,
  'getAvailableMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomerOrders' : ActorMethod<[string], Array<Order>>,
  'getMenuItem' : ActorMethod<[bigint], [] | [MenuItem]>,
  'getMenuItemCategories' : ActorMethod<[], Array<string>>,
  'getMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getMenuItemsByCategory' : ActorMethod<[string], Array<MenuItem>>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getOrderItems' : ActorMethod<[bigint], [] | [Array<OrderItem>]>,
  'getOrderStatus' : ActorMethod<[bigint], [] | [OrderStatus]>,
  'getOrderTotal' : ActorMethod<[bigint], [] | [number]>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getOrdersByStatus' : ActorMethod<[OrderStatus], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeMenuItem' : ActorMethod<[bigint], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchMenuItems' : ActorMethod<[string], Array<MenuItem>>,
  'updateMenuItem' : ActorMethod<
    [bigint, string, string, number, string, string, boolean],
    boolean
  >,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];